<?php
define('LN', "\n");
define('DEFAULT_FEATURE', 'weighted_completeness2');
$configuration = parse_ini_file('config.cfg');

$features = array(
  'total' => 'Every field',
  'mandatory' => 'Mandatory',
  'descriptiveness' => 'Descriptiveness',
  'searchability' => 'Searchability',
  'contextualization' => 'Contextualization',
  'identification' => 'Identification',
  'browsing' => 'Browsing',
  'viewing' => 'Viewing',
  'reusability' => 'Reusability',
  'multilinguality' => 'Multilinguality',

  'weighted_cardinality' => 'Completeness based on field cardinality',
  'weighted_completeness1' => 'Completeness based on subdimensions',
  'weighted_completeness2' => 'Completeness based in subdimensions and field cardinality',
  'completeness_proxy' => 'Completeness of Proxy',
  'completeness_aggregation' => 'Completeness of Aggregation',
  'completeness_agent' => 'Completeness of Agents',
  'completeness_place' => 'Completeness of Place',
  'completeness_timespan' => 'Completeness of Timespan',
  'completeness_concept' => 'Completeness of Concept',

  'saturation2_languages_per_property_in_providerproxy' => 'Multilinguality: Languages per property in provider proxy',
  'saturation2_languages_per_property_in_europeanaproxy' => 'Multilinguality: Languages per property in Europeana proxy',
  'saturation2_languages_per_property_in_object' => 'Multilinguality: Languages per property in object',
  'saturation2_taggedliterals_in_providerproxy' => 'Multilinguality: Tagged literals in provider proxy',
  'saturation2_taggedliterals_in_europeanaproxy' => 'Multilinguality: Tagged literals in Europeana proxy',
  'saturation2_taggedliterals_in_object' => 'Multilinguality: Tagged literals in object',
  'saturation2_distinctlanguages_in_providerproxy' => 'Multilinguality: Distinct languages in provider proxy',
  'saturation2_distinctlanguages_in_europeanaproxy' => 'Multilinguality: Distinct languages in Europeana proxy',
  'saturation2_distinctlanguages_in_object' => 'Multilinguality: Distinct languages in object',
  'saturation2_taggedliterals_per_language_in_providerproxy' => 'Multilinguality: Tagged literals per language in provider proxy',
  'saturation2_taggedliterals_per_language_in_europeanaproxy' => 'Multilinguality: Tagged literals per language in Europeana proxy',
  'saturation2_taggedliterals_per_language_in_object' => 'Multilinguality: Tagged literals per language in object',

/*
  'saturation_sum' => 'Multilingual saturation (cumulative)',
  'saturation_average' => 'Multilingual saturation (average)',
  'saturation_normalized' => 'Multilingual saturation (normalized average)',

  'entropy_dc_title_sum' => 'dc:title entropy - cumulative',
  'entropy_dc_title_avg' => 'dc:title entropy - average',
  'entropy_dcterms_alternative_sum' => 'dcterms:alternative entropy - cumulative',
  'entropy_dcterms_alternative_avg' => 'dctersm:alternative entorpy - average',
  'entropy_dc_description_sum' => 'dc:description entropy - cumulative',
  'entropy_dc_description_avg' => 'dc:description entorpy - average',
*/

  'crd_providedcho_rdf_about' => 'Cardinality of ProvidedCHO/rdf:about',
  'crd_proxy_dc_title' => 'Cardinality of Proxy/dc:title',
  'crd_proxy_dcterms_alternative' => 'Cardinality of Proxy/dcterms:alternative',
  'crd_proxy_dc_description' => 'Cardinality of Proxy/dc:description',
  'crd_proxy_dc_creator' => 'Cardinality of Proxy/dc:creator',
  'crd_proxy_dc_publisher' => 'Cardinality of Proxy/dc:publisher',
  'crd_proxy_dc_contributor' => 'Cardinality of Proxy/dc:contributor',
  'crd_proxy_dc_type' => 'Cardinality of Proxy/dc:type',
  'crd_proxy_dc_identifier' => 'Cardinality of Proxy/dc:identifier',
  'crd_proxy_dc_language' => 'Cardinality of Proxy/dc:language',
  'crd_proxy_dc_coverage' => 'Cardinality of Proxy/dc:coverage',
  'crd_proxy_dcterms_temporal' => 'Cardinality of Proxy/dcterms:temporal',
  'crd_proxy_dcterms_spatial' => 'Cardinality of Proxy/dcterms:spatial',
  'crd_proxy_dc_subject' => 'Cardinality of Proxy/dc:subject',
  'crd_proxy_dc_date' => 'Cardinality of Proxy/dc:date',
  'crd_proxy_dcterms_created' => 'Cardinality of Proxy/dcterms:created',
  'crd_proxy_dcterms_issued' => 'Cardinality of Proxy/dcterms:issued',
  'crd_proxy_dcterms_extent' => 'Cardinality of Proxy/dcterms:extent',
  'crd_proxy_dcterms_medium' => 'Cardinality of Proxy/dcterms:medium',
  'crd_proxy_dcterms_provenance' => 'Cardinality of Proxy/dcterms:provenance',
  'crd_proxy_dcterms_haspart' => 'Cardinality of Proxy/dcterms:hasPart',
  'crd_proxy_dcterms_ispartof' => 'Cardinality of Proxy/dcterms:isPartOf',
  'crd_proxy_dc_format' => 'Cardinality of Proxy/dc:format',
  'crd_proxy_dc_source' => 'Cardinality of Proxy/dc:source',
  'crd_proxy_dc_rights' => 'Cardinality of Proxy/dc:rights',
  'crd_proxy_dc_relation' => 'Cardinality of Proxy/dc:relation',
  'crd_proxy_edm_isnextinsequence' => 'Cardinality of Proxy/edm:isNextInSequence',
  'crd_proxy_edm_type' => 'Cardinality of Proxy/edm:type',
  'crd_proxy_edm_europeanaproxy' => 'Cardinality of Proxy/edm:europeanaProxy',
  'crd_proxy_edm_year' => 'Cardinality of Proxy/edm:year',
  'crd_proxy_edm_usertag' => 'Cardinality of Proxy/edm:userTag',
  'crd_proxy_ore_proxyin' => 'Cardinality of Proxy/ore:ProxyIn',
  'crd_proxy_ore_proxyfor' => 'Cardinality of Proxy/ore:ProxyFor',
  'crd_proxy_dc_conformsto' => 'Cardinality of Proxy/dc:conformsTo',
  'crd_proxy_dcterms_hasformat' => 'Cardinality of Proxy/dcterms:hasFormat',
  'crd_proxy_dcterms_hasversion' => 'Cardinality of Proxy/dcterms:hasVersion',
  'crd_proxy_dcterms_isformatof' => 'Cardinality of Proxy/dcterms:isFormatOf',
  'crd_proxy_dcterms_isreferencedby' => 'Cardinality of Proxy/dcterms:isReferencedBy',
  'crd_proxy_dcterms_isreplacedby' => 'Cardinality of Proxy/dcterms:isReplacedBy',
  'crd_proxy_dcterms_isrequiredby' => 'Cardinality of Proxy/dcterms:isRequiredBy',
  'crd_proxy_dcterms_isversionof' => 'Cardinality of Proxy/dcterms:isVersionOf',
  'crd_proxy_dcterms_references' => 'Cardinality of Proxy/dcterms:references',
  'crd_proxy_dcterms_replaces' => 'Cardinality of Proxy/dcterms:replaces',
  'crd_proxy_dcterms_requires' => 'Cardinality of Proxy/dcterms:requires',
  'crd_proxy_dcterms_tableofcontents' => 'Cardinality of Proxy/dcterms:tableOfContents',
  'crd_proxy_edm_currentlocation' => 'Cardinality of Proxy/edm:currentLocation',
  'crd_proxy_edm_hasmet' => 'Cardinality of Proxy/edm:hasMet',
  'crd_proxy_edm_hastype' => 'Cardinality of Proxy/edm:hasType',
  'crd_proxy_edm_incorporates' => 'Cardinality of Proxy/edm:incorporates',
  'crd_proxy_edm_isderivativeof' => 'Cardinality of Proxy/edm:isDerivativeOf',
  'crd_proxy_edm_isrelatedto' => 'Cardinality of Proxy/edm:isRelatedTo',
  'crd_proxy_edm_isrepresentationof' => 'Cardinality of Proxy/edm:isRepresentationOf',
  'crd_proxy_edm_issimilarto' => 'Cardinality of Proxy/edm:isSimilarTo',
  'crd_proxy_edm_issuccessorof' => 'Cardinality of Proxy/edm:isSuccessorOf',
  'crd_proxy_edm_realizes' => 'Cardinality of Proxy/edm:realizes',
  'crd_proxy_edm_waspresentat' => 'Cardinality of Proxy/edm:wasPresentAt',
  'crd_aggregation_edm_rights' => 'Cardinality of Aggregation/edm:rights',
  'crd_aggregation_edm_provider' => 'Cardinality of Aggregation/edm:provider',
  'crd_aggregation_edm_dataprovider' => 'Cardinality of Aggregation/edm:dataProvider',
  'crd_aggregation_edm_isshownat' => 'Cardinality of Aggregation/edm:isShownAt',
  'crd_aggregation_edm_isshownby' => 'Cardinality of Aggregation/edm:isShownBy',
  'crd_aggregation_edm_object' => 'Cardinality of Aggregation/edm:object',
  'crd_aggregation_edm_hasview' => 'Cardinality of Aggregation/edm:hasView',
  'crd_aggregation_dc_rights' => 'Cardinality of Aggregation/dc:rights',
  'crd_aggregation_edm_ugc' => 'Cardinality of Aggregation/edm:ugc',
  'crd_aggregation_edm_aggregatedcho' => 'Cardinality of Aggregation/edm:aggregatedCHO',
  'crd_aggregation_edm_intermediateprovider' => 'Cardinality of Aggregation/edm:intermediateProvider',
  'crd_aggregation_rdf_about' => 'Cardinality of Aggregation/rdf:about',
  'crd_place_wgs84_lat' => 'Cardinality of Place/wgs84:lat',
  'crd_place_wgs84_long' => 'Cardinality of Place/wgs84:long',
  'crd_place_wgs84_alt' => 'Cardinality of Place/wgs84:alt',
  'crd_place_dcterms_ispartof' => 'Cardinality of Place/dcterms:isPartOf',
  'crd_place_wgs84_pos_lat_long' => 'Cardinality of Place/wgs84:pos:lat:long',
  'crd_place_dcterms_haspart' => 'Cardinality of Place/dcterms:hasPart',
  'crd_place_owl_sameas' => 'Cardinality of Place/owl:sameAs',
  'crd_place_skos_preflabel' => 'Cardinality of Place/skos:prefLabel',
  'crd_place_skos_altlabel' => 'Cardinality of Place/skos:altLabel',
  'crd_place_skos_note' => 'Cardinality of Place/skos:note',
  'crd_place_rdf_about' => 'Cardinality of Place/rdf:about',
  'crd_agent_rdf_about' => 'Cardinality of Agent/rdf:about',
  'crd_agent_edm_begin' => 'Cardinality of Agent/edm:begin',
  'crd_agent_edm_end' => 'Cardinality of Agent/edm:end',
  'crd_agent_edm_hasmet' => 'Cardinality of Agent/edm:hasMet',
  'crd_agent_edm_isrelatedto' => 'Cardinality of Agent/edm:isRelatedTo',
  'crd_agent_owl_sameas' => 'Cardinality of Agent/owl:sameAs',
  'crd_agent_foaf_name' => 'Cardinality of Agent/foaf:name',
  'crd_agent_dc_date' => 'Cardinality of Agent/dc:date',
  'crd_agent_dc_identifier' => 'Cardinality of Agent/dc:identifier',
  'crd_agent_rdagr2_dateofbirth' => 'Cardinality of Agent/rdaGr2:dateOfBirth',
  'crd_agent_rdagr2_placeofbirth' => 'Cardinality of Agent/rdaGr2:placeOfBirth',
  'crd_agent_rdagr2_dateofdeath' => 'Cardinality of Agent/rdaGr2:dateOfDeath',
  'crd_agent_rdagr2_placeofdeath' => 'Cardinality of Agent/rdaGr2:placeOfDeath',
  'crd_agent_rdagr2_dateofestablishment' => 'Cardinality of Agent/rdaGr2:dateOfEstablishment',
  'crd_agent_rdagr2_dateoftermination' => 'Cardinality of Agent/rdaGr2:dateOfTermination',
  'crd_agent_rdagr2_gender' => 'Cardinality of Agent/rdaGr2:gender',
  'crd_agent_rdagr2_professionoroccupation' => 'Cardinality of Agent/rdaGr2:professionOrOccupation',
  'crd_agent_rdagr2_biographicalinformation' => 'Cardinality of Agent/rdaGr2:biographicalInformation',
  'crd_agent_skos_preflabel' => 'Cardinality of Agent/skos:prefLabel',
  'crd_agent_skos_altlabel' => 'Cardinality of Agent/skos:altLabel',
  'crd_agent_skos_note' => 'Cardinality of Agent/skos:note',
  'crd_timespan_rdf_about' => 'Cardinality of Timespan/rdf:about',
  'crd_timespan_edm_begin' => 'Cardinality of Timespan/edm:begin',
  'crd_timespan_edm_end' => 'Cardinality of Timespan/edm:end',
  'crd_timespan_dcterms_ispartof' => 'Cardinality of Timespan/dcterms:isPartOf',
  'crd_timespan_dcterms_haspart' => 'Cardinality of Timespan/dcterms:hasPart',
  'crd_timespan_edm_isnextinsequence' => 'Cardinality of Timespan/edm:isNextInSequence',
  'crd_timespan_owl_sameas' => 'Cardinality of Timespan/owl:sameAs',
  'crd_timespan_skos_preflabel' => 'Cardinality of Timespan/skos:prefLabel',
  'crd_timespan_skos_altlabel' => 'Cardinality of Timespan/skos:altLabel',
  'crd_timespan_skos_note' => 'Cardinality of Timespan/skos:note',
  'crd_concept_rdf_about' => 'Cardinality of Concept/rdf:about',
  'crd_concept_skos_broader' => 'Cardinality of Concept/skos:broader',
  'crd_concept_skos_narrower' => 'Cardinality of Concept/skos:narrower',
  'crd_concept_skos_related' => 'Cardinality of Concept/skos:related',
  'crd_concept_skos_broadmatch' => 'Cardinality of Concept/skos:broadMatch',
  'crd_concept_skos_narrowmatch' => 'Cardinality of Concept/skos:narrowMatch',
  'crd_concept_skos_relatedmatch' => 'Cardinality of Concept/skos:relatedMatch',
  'crd_concept_skos_exactmatch' => 'Cardinality of Concept/skos:exactMatch',
  'crd_concept_skos_closematch' => 'Cardinality of Concept/skos:closeMatch',
  'crd_concept_skos_notation' => 'Cardinality of Concept/skos:notation',
  'crd_concept_skos_inscheme' => 'Cardinality of Concept/skos:inScheme',
  'crd_concept_skos_preflabel' => 'Cardinality of Concept/skos:prefLabel',
  'crd_concept_skos_altlabel' => 'Cardinality of Concept/skos:altLabel',
  'crd_concept_skos_note' => 'Cardinality of Concept/skos:note',

  'saturation_sum_proxy_dc_title' => 'Multilingual saturation of Proxy/dc:title (sum)',
  'saturation_average_proxy_dc_title' => 'Multilingual saturation of Proxy/dc:title (average)',
  'saturation_normalized_proxy_dc_title' => 'Multilingual saturation of Proxy/dc:title (normalized average)',
  'saturation_sum_proxy_dcterms_alternative' => 'Multilingual saturation of Proxy/dcterms:alternative (sum)',
  'saturation_average_proxy_dcterms_alternative' => 'Multilingual saturation of Proxy/dcterms:alternative (average)',
  'saturation_normalized_proxy_dcterms_alternative' => 'Multilingual saturation of Proxy/dcterms:alternative (normalized average)',
  'saturation_sum_proxy_dc_description' => 'Multilingual saturation of Proxy/dc:description (sum)',
  'saturation_average_proxy_dc_description' => 'Multilingual saturation of Proxy/dc:description (average)',
  'saturation_normalized_proxy_dc_description' => 'Multilingual saturation of Proxy/dc:description (normalized average)',
  'saturation_sum_proxy_dc_creator' => 'Multilingual saturation of Proxy/dc:creator (sum)',
  'saturation_average_proxy_dc_creator' => 'Multilingual saturation of Proxy/dc:creator (average)',
  'saturation_normalized_proxy_dc_creator' => 'Multilingual saturation of Proxy/dc:creator (normalized average)',
  'saturation_sum_proxy_dc_publisher' => 'Multilingual saturation of Proxy/dc:publisher (sum)',
  'saturation_average_proxy_dc_publisher' => 'Multilingual saturation of Proxy/dc:publisher (average)',
  'saturation_normalized_proxy_dc_publisher' => 'Multilingual saturation of Proxy/dc:publisher (normalized average)',
  'saturation_sum_proxy_dc_contributor' => 'Multilingual saturation of Proxy/dc:contributor (sum)',
  'saturation_average_proxy_dc_contributor' => 'Multilingual saturation of Proxy/dc:contributor (average)',
  'saturation_normalized_proxy_dc_contributor' => 'Multilingual saturation of Proxy/dc:contributor (normalized average)',
  'saturation_sum_proxy_dc_type' => 'Multilingual saturation of Proxy/dc:type (sum)',
  'saturation_average_proxy_dc_type' => 'Multilingual saturation of Proxy/dc:type (average)',
  'saturation_normalized_proxy_dc_type' => 'Multilingual saturation of Proxy/dc:type (normalized average)',
  'saturation_sum_proxy_dc_identifier' => 'Multilingual saturation of Proxy/dc:identifier (sum)',
  'saturation_average_proxy_dc_identifier' => 'Multilingual saturation of Proxy/dc:identifier (average)',
  'saturation_normalized_proxy_dc_identifier' => 'Multilingual saturation of Proxy/dc:identifier (normalized average)',
  'saturation_sum_proxy_dc_language' => 'Multilingual saturation of Proxy/dc:language (sum)',
  'saturation_average_proxy_dc_language' => 'Multilingual saturation of Proxy/dc:language (average)',
  'saturation_normalized_proxy_dc_language' => 'Multilingual saturation of Proxy/dc:language (normalized average)',
  'saturation_sum_proxy_dc_coverage' => 'Multilingual saturation of Proxy/dc:coverage (sum)',
  'saturation_average_proxy_dc_coverage' => 'Multilingual saturation of Proxy/dc:coverage (average)',
  'saturation_normalized_proxy_dc_coverage' => 'Multilingual saturation of Proxy/dc:coverage (normalized average)',
  'saturation_sum_proxy_dcterms_temporal' => 'Multilingual saturation of Proxy/dcterms:temporal (sum)',
  'saturation_average_proxy_dcterms_temporal' => 'Multilingual saturation of Proxy/dcterms:temporal (average)',
  'saturation_normalized_proxy_dcterms_temporal' => 'Multilingual saturation of Proxy/dcterms:temporal (normalized average)',
  'saturation_sum_proxy_dcterms_spatial' => 'Multilingual saturation of Proxy/dcterms:spatial (sum)',
  'saturation_average_proxy_dcterms_spatial' => 'Multilingual saturation of Proxy/dcterms:spatial (average)',
  'saturation_normalized_proxy_dcterms_spatial' => 'Multilingual saturation of Proxy/dcterms:spatial (normalized average)',
  'saturation_sum_proxy_dc_subject' => 'Multilingual saturation of Proxy/dc:subject (sum)',
  'saturation_average_proxy_dc_subject' => 'Multilingual saturation of Proxy/dc:subject (average)',
  'saturation_normalized_proxy_dc_subject' => 'Multilingual saturation of Proxy/dc:subject (normalized average)',
  'saturation_sum_proxy_dc_date' => 'Multilingual saturation of Proxy/dc:date (sum)',
  'saturation_average_proxy_dc_date' => 'Multilingual saturation of Proxy/dc:date (average)',
  'saturation_normalized_proxy_dc_date' => 'Multilingual saturation of Proxy/dc:date (normalized average)',
  'saturation_sum_proxy_dcterms_created' => 'Multilingual saturation of Proxy/dcterms:created (sum)',
  'saturation_average_proxy_dcterms_created' => 'Multilingual saturation of Proxy/dcterms:created (average)',
  'saturation_normalized_proxy_dcterms_created' => 'Multilingual saturation of Proxy/dcterms:created (normalized average)',
  'saturation_sum_proxy_dcterms_issued' => 'Multilingual saturation of Proxy/dcterms:issued (sum)',
  'saturation_average_proxy_dcterms_issued' => 'Multilingual saturation of Proxy/dcterms:issued (average)',
  'saturation_normalized_proxy_dcterms_issued' => 'Multilingual saturation of Proxy/dcterms:issued (normalized average)',
  'saturation_sum_proxy_dcterms_extent' => 'Multilingual saturation of Proxy/dcterms:extent (sum)',
  'saturation_average_proxy_dcterms_extent' => 'Multilingual saturation of Proxy/dcterms:extent (average)',
  'saturation_normalized_proxy_dcterms_extent' => 'Multilingual saturation of Proxy/dcterms:extent (normalized average)',
  'saturation_sum_proxy_dcterms_medium' => 'Multilingual saturation of Proxy/dcterms:medium (sum)',
  'saturation_average_proxy_dcterms_medium' => 'Multilingual saturation of Proxy/dcterms:medium (average)',
  'saturation_normalized_proxy_dcterms_medium' => 'Multilingual saturation of Proxy/dcterms:medium (normalized average)',
  'saturation_sum_proxy_dcterms_provenance' => 'Multilingual saturation of Proxy/dcterms:provenance (sum)',
  'saturation_average_proxy_dcterms_provenance' => 'Multilingual saturation of Proxy/dcterms:provenance (average)',
  'saturation_normalized_proxy_dcterms_provenance' => 'Multilingual saturation of Proxy/dcterms:provenance (normalized average)',
  'saturation_sum_proxy_dcterms_haspart' => 'Multilingual saturation of Proxy/dcterms:hasPart (sum)',
  'saturation_average_proxy_dcterms_haspart' => 'Multilingual saturation of Proxy/dcterms:hasPart (average)',
  'saturation_normalized_proxy_dcterms_haspart' => 'Multilingual saturation of Proxy/dcterms:hasPart (normalized average)',
  'saturation_sum_proxy_dcterms_ispartof' => 'Multilingual saturation of Proxy/dcterms:isPartOf (sum)',
  'saturation_average_proxy_dcterms_ispartof' => 'Multilingual saturation of Proxy/dcterms:isPartOf (average)',
  'saturation_normalized_proxy_dcterms_ispartof' => 'Multilingual saturation of Proxy/dcterms:isPartOf (normalized average)',
  'saturation_sum_proxy_dc_format' => 'Multilingual saturation of Proxy/dc:format (sum)',
  'saturation_average_proxy_dc_format' => 'Multilingual saturation of Proxy/dc:format (average)',
  'saturation_normalized_proxy_dc_format' => 'Multilingual saturation of Proxy/dc:format (normalized average)',
  'saturation_sum_proxy_dc_source' => 'Multilingual saturation of Proxy/dc:source (sum)',
  'saturation_average_proxy_dc_source' => 'Multilingual saturation of Proxy/dc:source (average)',
  'saturation_normalized_proxy_dc_source' => 'Multilingual saturation of Proxy/dc:source (normalized average)',
  'saturation_sum_proxy_dc_rights' => 'Multilingual saturation of Proxy/dc:rights (sum)',
  'saturation_average_proxy_dc_rights' => 'Multilingual saturation of Proxy/dc:rights (average)',
  'saturation_normalized_proxy_dc_rights' => 'Multilingual saturation of Proxy/dc:rights (normalized average)',
  'saturation_sum_proxy_dc_relation' => 'Multilingual saturation of Proxy/dc:relation (sum)',
  'saturation_average_proxy_dc_relation' => 'Multilingual saturation of Proxy/dc:relation (average)',
  'saturation_normalized_proxy_dc_relation' => 'Multilingual saturation of Proxy/dc:relation (normalized average)',
  'saturation_sum_proxy_edm_europeanaproxy' => 'Multilingual saturation of Proxy/edm:europeanaProxy (sum)',
  'saturation_average_proxy_edm_europeanaproxy' => 'Multilingual saturation of Proxy/edm:europeanaProxy (average)',
  'saturation_normalized_proxy_edm_europeanaproxy' => 'Multilingual saturation of Proxy/edm:europeanaProxy (normalized average)',
  'saturation_sum_proxy_edm_year' => 'Multilingual saturation of Proxy/edm:year (sum)',
  'saturation_average_proxy_edm_year' => 'Multilingual saturation of Proxy/edm:year (average)',
  'saturation_normalized_proxy_edm_year' => 'Multilingual saturation of Proxy/edm:year (normalized average)',
  'saturation_sum_proxy_edm_usertag' => 'Multilingual saturation of Proxy/edm:userTag (sum)',
  'saturation_average_proxy_edm_usertag' => 'Multilingual saturation of Proxy/edm:userTag (average)',
  'saturation_normalized_proxy_edm_usertag' => 'Multilingual saturation of Proxy/edm:userTag (normalized average)',
  'saturation_sum_proxy_ore_proxyin' => 'Multilingual saturation of Proxy/ore:proxyIn (sum)',
  'saturation_average_proxy_ore_proxyin' => 'Multilingual saturation of Proxy/ore:proxyIn (average)',
  'saturation_normalized_proxy_ore_proxyin' => 'Multilingual saturation of Proxy/ore:proxyIn (normalized average)',
  'saturation_sum_proxy_ore_proxyfor' => 'Multilingual saturation of Proxy/ore:proxyFor (sum)',
  'saturation_average_proxy_ore_proxyfor' => 'Multilingual saturation of Proxy/ore:proxyFor (average)',
  'saturation_normalized_proxy_ore_proxyfor' => 'Multilingual saturation of Proxy/ore:proxyFor (normalized average)',
  'saturation_sum_proxy_dcterms_conformsto' => 'Multilingual saturation of Proxy/dcterms:conformsTo (sum)',
  'saturation_average_proxy_dcterms_conformsto' => 'Multilingual saturation of Proxy/dcterms:conformsTo (average)',
  'saturation_normalized_proxy_dcterms_conformsto' => 'Multilingual saturation of Proxy/dcterms:conformsTo (normalized average)',
  'saturation_sum_proxy_dcterms_hasformat' => 'Multilingual saturation of Proxy/dcterms:hasFormat (sum)',
  'saturation_average_proxy_dcterms_hasformat' => 'Multilingual saturation of Proxy/dcterms:hasFormat (average)',
  'saturation_normalized_proxy_dcterms_hasformat' => 'Multilingual saturation of Proxy/dcterms:hasFormat (normalized average)',
  'saturation_sum_proxy_dcterms_hasversion' => 'Multilingual saturation of Proxy/dcterms:hasVersion (sum)',
  'saturation_average_proxy_dcterms_hasversion' => 'Multilingual saturation of Proxy/dcterms:hasVersion (average)',
  'saturation_normalized_proxy_dcterms_hasversion' => 'Multilingual saturation of Proxy/dcterms:hasVersion (normalized average)',
  'saturation_sum_proxy_dcterms_isformatof' => 'Multilingual saturation of Proxy/dcterms:isFormatOf (sum)',
  'saturation_average_proxy_dcterms_isformatof' => 'Multilingual saturation of Proxy/dcterms:isFormatOf (average)',
  'saturation_normalized_proxy_dcterms_isformatof' => 'Multilingual saturation of Proxy/dcterms:isFormatOf (normalized average)',
  'saturation_sum_proxy_dcterms_isreferencedby' => 'Multilingual saturation of Proxy/dcterms:isReferencedBy (sum)',
  'saturation_average_proxy_dcterms_isreferencedby' => 'Multilingual saturation of Proxy/dcterms:isReferencedBy (average)',
  'saturation_normalized_proxy_dcterms_isreferencedby' => 'Multilingual saturation of Proxy/dcterms:isReferencedBy (normalized average)',
  'saturation_sum_proxy_dcterms_isreplacedby' => 'Multilingual saturation of Proxy/dcterms:isReplacedBy (sum)',
  'saturation_average_proxy_dcterms_isreplacedby' => 'Multilingual saturation of Proxy/dcterms:isReplacedBy (average)',
  'saturation_normalized_proxy_dcterms_isreplacedby' => 'Multilingual saturation of Proxy/dcterms:isReplacedBy (normalized average)',
  'saturation_sum_proxy_dcterms_isrequiredby' => 'Multilingual saturation of Proxy/dcterms:isRequiredBy (sum)',
  'saturation_average_proxy_dcterms_isrequiredby' => 'Multilingual saturation of Proxy/dcterms:isRequiredBy (average)',
  'saturation_normalized_proxy_dcterms_isrequiredby' => 'Multilingual saturation of Proxy/dcterms:isRequiredBy (normalized average)',
  'saturation_sum_proxy_dcterms_isversionof' => 'Multilingual saturation of Proxy/dcterms:isVersionOf (sum)',
  'saturation_average_proxy_dcterms_isversionof' => 'Multilingual saturation of Proxy/dcterms:isVersionOf (average)',
  'saturation_normalized_proxy_dcterms_isversionof' => 'Multilingual saturation of Proxy/dcterms:isVersionOf (normalized average)',
  'saturation_sum_proxy_dcterms_references' => 'Multilingual saturation of Proxy/dcterms:references (sum)',
  'saturation_average_proxy_dcterms_references' => 'Multilingual saturation of Proxy/dcterms:references (average)',
  'saturation_normalized_proxy_dcterms_references' => 'Multilingual saturation of Proxy/dcterms:references (normalized average)',
  'saturation_sum_proxy_dcterms_replaces' => 'Multilingual saturation of Proxy/dcterms:replaces (sum)',
  'saturation_average_proxy_dcterms_replaces' => 'Multilingual saturation of Proxy/dcterms:replaces (average)',
  'saturation_normalized_proxy_dcterms_replaces' => 'Multilingual saturation of Proxy/dcterms:replaces (normalized average)',
  'saturation_sum_proxy_dcterms_requires' => 'Multilingual saturation of Proxy/dcterms:requires (sum)',
  'saturation_average_proxy_dcterms_requires' => 'Multilingual saturation of Proxy/dcterms:requires (average)',
  'saturation_normalized_proxy_dcterms_requires' => 'Multilingual saturation of Proxy/dcterms:requires (normalized average)',
  'saturation_sum_proxy_dcterms_tableofcontents' => 'Multilingual saturation of Proxy/dcterms:tableOfContents (sum)',
  'saturation_average_proxy_dcterms_tableofcontents' => 'Multilingual saturation of Proxy/dcterms:tableOfContents (average)',
  'saturation_normalized_proxy_dcterms_tableofcontents' => 'Multilingual saturation of Proxy/dcterms:tableOfContents (normalized average)',
  'saturation_sum_proxy_edm_currentlocation' => 'Multilingual saturation of Proxy/edm:currentLocation (sum)',
  'saturation_average_proxy_edm_currentlocation' => 'Multilingual saturation of Proxy/edm:currentLocation (average)',
  'saturation_normalized_proxy_edm_currentlocation' => 'Multilingual saturation of Proxy/edm:currentLocation (normalized average)',
  'saturation_sum_proxy_edm_hasmet' => 'Multilingual saturation of Proxy/edm:hasMet (sum)',
  'saturation_average_proxy_edm_hasmet' => 'Multilingual saturation of Proxy/edm:hasMet (average)',
  'saturation_normalized_proxy_edm_hasmet' => 'Multilingual saturation of Proxy/edm:hasMet (normalized average)',
  'saturation_sum_proxy_edm_hastype' => 'Multilingual saturation of Proxy/edm:hasType (sum)',
  'saturation_average_proxy_edm_hastype' => 'Multilingual saturation of Proxy/edm:hasType (average)',
  'saturation_normalized_proxy_edm_hastype' => 'Multilingual saturation of Proxy/edm:hasType (normalized average)',
  'saturation_sum_proxy_edm_incorporates' => 'Multilingual saturation of Proxy/edm:incorporates (sum)',
  'saturation_average_proxy_edm_incorporates' => 'Multilingual saturation of Proxy/edm:incorporates (average)',
  'saturation_normalized_proxy_edm_incorporates' => 'Multilingual saturation of Proxy/edm:incorporates (normalized average)',
  'saturation_sum_proxy_edm_isderivativeof' => 'Multilingual saturation of Proxy/edm:isDerivativeOf (sum)',
  'saturation_average_proxy_edm_isderivativeof' => 'Multilingual saturation of Proxy/edm:isDerivativeOf (average)',
  'saturation_normalized_proxy_edm_isderivativeof' => 'Multilingual saturation of Proxy/edm:isDerivativeOf (normalized average)',
  'saturation_sum_proxy_edm_isrelatedto' => 'Multilingual saturation of Proxy/edm:isRelatedTo (sum)',
  'saturation_average_proxy_edm_isrelatedto' => 'Multilingual saturation of Proxy/edm:isRelatedTo (average)',
  'saturation_normalized_proxy_edm_isrelatedto' => 'Multilingual saturation of Proxy/edm:isRelatedTo (normalized average)',
  'saturation_sum_proxy_edm_isrepresentationof' => 'Multilingual saturation of Proxy/edm:isRepresentationOf (sum)',
  'saturation_average_proxy_edm_isrepresentationof' => 'Multilingual saturation of Proxy/edm:isRepresentationOf (average)',
  'saturation_normalized_proxy_edm_isrepresentationof' => 'Multilingual saturation of Proxy/edm:isRepresentationOf (normalized average)',
  'saturation_sum_proxy_edm_issimilarto' => 'Multilingual saturation of Proxy/edm:isSimilarTo (sum)',
  'saturation_average_proxy_edm_issimilarto' => 'Multilingual saturation of Proxy/edm:isSimilarTo (average)',
  'saturation_normalized_proxy_edm_issimilarto' => 'Multilingual saturation of Proxy/edm:isSimilarTo (normalized average)',
  'saturation_sum_proxy_edm_issuccessorof' => 'Multilingual saturation of Proxy/edm:isSuccessorOf (sum)',
  'saturation_average_proxy_edm_issuccessorof' => 'Multilingual saturation of Proxy/edm:isSuccessorOf (average)',
  'saturation_normalized_proxy_edm_issuccessorof' => 'Multilingual saturation of Proxy/edm:isSuccessorOf (normalized average)',
  'saturation_sum_proxy_edm_realizes' => 'Multilingual saturation of Proxy/edm:realizes (sum)',
  'saturation_average_proxy_edm_realizes' => 'Multilingual saturation of Proxy/edm:realizes (average)',
  'saturation_normalized_proxy_edm_realizes' => 'Multilingual saturation of Proxy/edm:realizes (normalized average)',
  'saturation_sum_proxy_edm_waspresentat' => 'Multilingual saturation of Proxy/edm:wasPresentAt (sum)',
  'saturation_average_proxy_edm_waspresentat' => 'Multilingual saturation of Proxy/edm:wasPresentAt (average)',
  'saturation_normalized_proxy_edm_waspresentat' => 'Multilingual saturation of Proxy/edm:wasPresentAt (normalized average)',
  'saturation_sum_aggregation_edm_rights' => 'Multilingual saturation of Aggregation/edm:rights (sum)',
  'saturation_average_aggregation_edm_rights' => 'Multilingual saturation of Aggregation/edm:rights (average)',
  'saturation_normalized_aggregation_edm_rights' => 'Multilingual saturation of Aggregation/edm:rights (normalized average)',
  'saturation_sum_aggregation_edm_provider' => 'Multilingual saturation of Aggregation/edm:provider (sum)',
  'saturation_average_aggregation_edm_provider' => 'Multilingual saturation of Aggregation/edm:provider (average)',
  'saturation_normalized_aggregation_edm_provider' => 'Multilingual saturation of Aggregation/edm:provider (normalized average)',
  'saturation_sum_aggregation_edm_dataprovider' => 'Multilingual saturation of Aggregation/edm:dataProvider (sum)',
  'saturation_average_aggregation_edm_dataprovider' => 'Multilingual saturation of Aggregation/edm:dataProvider (average)',
  'saturation_normalized_aggregation_edm_dataprovider' => 'Multilingual saturation of Aggregation/edm:dataProvider (normalized average)',
  'saturation_sum_aggregation_dc_rights' => 'Multilingual saturation of Aggregation/dc:rights (sum)',
  'saturation_average_aggregation_dc_rights' => 'Multilingual saturation of Aggregation/dc:rights (average)',
  'saturation_normalized_aggregation_dc_rights' => 'Multilingual saturation of Aggregation/dc:rights (normalized average)',
  'saturation_sum_aggregation_edm_ugc' => 'Multilingual saturation of Aggregation/edm:ugc (sum)',
  'saturation_average_aggregation_edm_ugc' => 'Multilingual saturation of Aggregation/edm:ugc (average)',
  'saturation_normalized_aggregation_edm_ugc' => 'Multilingual saturation of Aggregation/edm:ugc (normalized average)',
  'saturation_sum_aggregation_edm_aggregatedcho' => 'Multilingual saturation of Aggregation/edm:aggregatedCHO (sum)',
  'saturation_average_aggregation_edm_aggregatedcho' => 'Multilingual saturation of Aggregation/edm:aggregatedCHO (average)',
  'saturation_normalized_aggregation_edm_aggregatedcho' => 'Multilingual saturation of Aggregation/edm:aggregatedCHO (normalized average)',
  'saturation_sum_aggregation_edm_intermediateprovider' => 'Multilingual saturation of Aggregation/edm:intermediateProvider (sum)',
  'saturation_average_aggregation_edm_intermediateprovider' => 'Multilingual saturation of Aggregation/edm:intermediateProvider (average)',
  'saturation_normalized_aggregation_edm_intermediateprovider' => 'Multilingual saturation of Aggregation/edm:intermediateProvider (normalized average)',
  'saturation_sum_place_dcterms_ispartof' => 'Multilingual saturation of Place/dcterms:isPartOf (sum)',
  'saturation_average_place_dcterms_ispartof' => 'Multilingual saturation of Place/dcterms:isPartOf (average)',
  'saturation_normalized_place_dcterms_ispartof' => 'Multilingual saturation of Place/dcterms:isPartOf (normalized average)',
  'saturation_sum_place_dcterms_haspart' => 'Multilingual saturation of Place/dcterms:hasPart (sum)',
  'saturation_average_place_dcterms_haspart' => 'Multilingual saturation of Place/dcterms:hasPart (average)',
  'saturation_normalized_place_dcterms_haspart' => 'Multilingual saturation of Place/dcterms:hasPart (normalized average)',
  'saturation_sum_place_skos_preflabel' => 'Multilingual saturation of Place/skos:prefLabel (sum)',
  'saturation_average_place_skos_preflabel' => 'Multilingual saturation of Place/skos:prefLabel (average)',
  'saturation_normalized_place_skos_preflabel' => 'Multilingual saturation of Place/skos:prefLabel (normalized average)',
  'saturation_sum_place_skos_altlabel' => 'Multilingual saturation of Place/skos:altLabel (sum)',
  'saturation_average_place_skos_altlabel' => 'Multilingual saturation of Place/skos:altLabel (average)',
  'saturation_normalized_place_skos_altlabel' => 'Multilingual saturation of Place/skos:altLabel (normalized average)',
  'saturation_sum_place_skos_note' => 'Multilingual saturation of Place/skos:note (sum)',
  'saturation_average_place_skos_note' => 'Multilingual saturation of Place/skos:note (average)',
  'saturation_normalized_place_skos_note' => 'Multilingual saturation of Place/skos:note (normalized average)',
  'saturation_sum_agent_edm_begin' => 'Multilingual saturation of Agent/edm:begin (sum)',
  'saturation_average_agent_edm_begin' => 'Multilingual saturation of Agent/edm:begin (average)',
  'saturation_normalized_agent_edm_begin' => 'Multilingual saturation of Agent/edm:begin (normalized average)',
  'saturation_sum_agent_edm_end' => 'Multilingual saturation of Agent/edm:end (sum)',
  'saturation_average_agent_edm_end' => 'Multilingual saturation of Agent/edm:end (average)',
  'saturation_normalized_agent_edm_end' => 'Multilingual saturation of Agent/edm:end (normalized average)',
  'saturation_sum_agent_edm_hasmet' => 'Multilingual saturation of Agent/edm:hasMet (sum)',
  'saturation_average_agent_edm_hasmet' => 'Multilingual saturation of Agent/edm:hasMet (average)',
  'saturation_normalized_agent_edm_hasmet' => 'Multilingual saturation of Agent/edm:hasMet (normalized average)',
  'saturation_sum_agent_edm_isrelatedto' => 'Multilingual saturation of Agent/edm:isRelatedTo (sum)',
  'saturation_average_agent_edm_isrelatedto' => 'Multilingual saturation of Agent/edm:isRelatedTo (average)',
  'saturation_normalized_agent_edm_isrelatedto' => 'Multilingual saturation of Agent/edm:isRelatedTo (normalized average)',
  'saturation_sum_agent_owl_sameas' => 'Multilingual saturation of Agent/owl:sameAs (sum)',
  'saturation_average_agent_owl_sameas' => 'Multilingual saturation of Agent/owl:sameAs (average)',
  'saturation_normalized_agent_owl_sameas' => 'Multilingual saturation of Agent/owl:sameAs (normalized average)',
  'saturation_sum_agent_foaf_name' => 'Multilingual saturation of Agent/foaf:name (sum)',
  'saturation_average_agent_foaf_name' => 'Multilingual saturation of Agent/foaf:name (average)',
  'saturation_normalized_agent_foaf_name' => 'Multilingual saturation of Agent/foaf:name (normalized average)',
  'saturation_sum_agent_dc_date' => 'Multilingual saturation of Agent/dc:date (sum)',
  'saturation_average_agent_dc_date' => 'Multilingual saturation of Agent/dc:date (average)',
  'saturation_normalized_agent_dc_date' => 'Multilingual saturation of Agent/dc:date (normalized average)',
  'saturation_sum_agent_dc_identifier' => 'Multilingual saturation of Agent/dc:identifier (sum)',
  'saturation_average_agent_dc_identifier' => 'Multilingual saturation of Agent/dc:identifier (average)',
  'saturation_normalized_agent_dc_identifier' => 'Multilingual saturation of Agent/dc:identifier (normalized average)',
  'saturation_sum_agent_rdagr2_dateofbirth' => 'Multilingual saturation of Agent/rdaGr2:dateOfBirth (sum)',
  'saturation_average_agent_rdagr2_dateofbirth' => 'Multilingual saturation of Agent/rdaGr2:dateOfBirth (average)',
  'saturation_normalized_agent_rdagr2_dateofbirth' => 'Multilingual saturation of Agent/rdaGr2:dateOfBirth (normalized average)',
  'saturation_sum_agent_rdagr2_placeofbirth' => 'Multilingual saturation of Agent/rdaGr2:placeOfBirth (sum)',
  'saturation_average_agent_rdagr2_placeofbirth' => 'Multilingual saturation of Agent/rdaGr2:placeOfBirth (average)',
  'saturation_normalized_agent_rdagr2_placeofbirth' => 'Multilingual saturation of Agent/rdaGr2:placeOfBirth (normalized average)',
  'saturation_sum_agent_rdagr2_dateofdeath' => 'Multilingual saturation of Agent/rdaGr2:dateOfDeath (sum)',
  'saturation_average_agent_rdagr2_dateofdeath' => 'Multilingual saturation of Agent/rdaGr2:dateOfDeath (average)',
  'saturation_normalized_agent_rdagr2_dateofdeath' => 'Multilingual saturation of Agent/rdaGr2:dateOfDeath (normalized average)',
  'saturation_sum_agent_rdagr2_placeofdeath' => 'Multilingual saturation of Agent/rdaGr2:placeOfDeath (sum)',
  'saturation_average_agent_rdagr2_placeofdeath' => 'Multilingual saturation of Agent/rdaGr2:placeOfDeath (average)',
  'saturation_normalized_agent_rdagr2_placeofdeath' => 'Multilingual saturation of Agent/rdaGr2:placeOfDeath (normalized average)',
  'saturation_sum_agent_rdagr2_dateofestablishment' => 'Multilingual saturation of Agent/rdaGr2:dateOfEstablishment (sum)',
  'saturation_average_agent_rdagr2_dateofestablishment' => 'Multilingual saturation of Agent/rdaGr2:dateOfEstablishment (average)',
  'saturation_normalized_agent_rdagr2_dateofestablishment' => 'Multilingual saturation of Agent/rdaGr2:dateOfEstablishment (normalized average)',
  'saturation_sum_agent_rdagr2_dateoftermination' => 'Multilingual saturation of Agent/rdaGr2:dateOfTermination (sum)',
  'saturation_average_agent_rdagr2_dateoftermination' => 'Multilingual saturation of Agent/rdaGr2:dateOfTermination (average)',
  'saturation_normalized_agent_rdagr2_dateoftermination' => 'Multilingual saturation of Agent/rdaGr2:dateOfTermination (normalized average)',
  'saturation_sum_agent_rdagr2_gender' => 'Multilingual saturation of Agent/rdaGr2:gender (sum)',
  'saturation_average_agent_rdagr2_gender' => 'Multilingual saturation of Agent/rdaGr2:gender (average)',
  'saturation_normalized_agent_rdagr2_gender' => 'Multilingual saturation of Agent/rdaGr2:gender (normalized average)',
  'saturation_sum_agent_rdagr2_professionoroccupation' => 'Multilingual saturation of Agent/rdaGr2:professionOrOccupation (sum)',
  'saturation_average_agent_rdagr2_professionoroccupation' => 'Multilingual saturation of Agent/rdaGr2:professionOrOccupation (average)',
  'saturation_normalized_agent_rdagr2_professionoroccupation' => 'Multilingual saturation of Agent/rdaGr2:professionOrOccupation (normalized average)',
  'saturation_sum_agent_rdagr2_biographicalinformation' => 'Multilingual saturation of Agent/rdaGr2:biographicalInformation (sum)',
  'saturation_average_agent_rdagr2_biographicalinformation' => 'Multilingual saturation of Agent/rdaGr2:biographicalInformation (average)',
  'saturation_normalized_agent_rdagr2_biographicalinformation' => 'Multilingual saturation of Agent/rdaGr2:biographicalInformation (normalized average)',
  'saturation_sum_agent_skos_preflabel' => 'Multilingual saturation of Agent/skos:prefLabel (sum)',
  'saturation_average_agent_skos_preflabel' => 'Multilingual saturation of Agent/skos:prefLabel (average)',
  'saturation_normalized_agent_skos_preflabel' => 'Multilingual saturation of Agent/skos:prefLabel (normalized average)',
  'saturation_sum_agent_skos_altlabel' => 'Multilingual saturation of Agent/skos:altLabel (sum)',
  'saturation_average_agent_skos_altlabel' => 'Multilingual saturation of Agent/skos:altLabel (average)',
  'saturation_normalized_agent_skos_altlabel' => 'Multilingual saturation of Agent/skos:altLabel (normalized average)',
  'saturation_sum_agent_skos_note' => 'Multilingual saturation of Agent/skos:note (sum)',
  'saturation_average_agent_skos_note' => 'Multilingual saturation of Agent/skos:note (average)',
  'saturation_normalized_agent_skos_note' => 'Multilingual saturation of Agent/skos:note (normalized average)',
  'saturation_sum_timespan_edm_begin' => 'Multilingual saturation of Timespan/edm:begin (sum)',
  'saturation_average_timespan_edm_begin' => 'Multilingual saturation of Timespan/edm:begin (average)',
  'saturation_normalized_timespan_edm_begin' => 'Multilingual saturation of Timespan/edm:begin (normalized average)',
  'saturation_sum_timespan_edm_end' => 'Multilingual saturation of Timespan/edm:end (sum)',
  'saturation_average_timespan_edm_end' => 'Multilingual saturation of Timespan/edm:end (average)',
  'saturation_normalized_timespan_edm_end' => 'Multilingual saturation of Timespan/edm:end (normalized average)',
  'saturation_sum_timespan_dcterms_ispartof' => 'Multilingual saturation of Timespan/dcterms:isPartOf (sum)',
  'saturation_average_timespan_dcterms_ispartof' => 'Multilingual saturation of Timespan/dcterms:isPartOf (average)',
  'saturation_normalized_timespan_dcterms_ispartof' => 'Multilingual saturation of Timespan/dcterms:isPartOf (normalized average)',
  'saturation_sum_timespan_dcterms_haspart' => 'Multilingual saturation of Timespan/dcterms:hasPart (sum)',
  'saturation_average_timespan_dcterms_haspart' => 'Multilingual saturation of Timespan/dcterms:hasPart (average)',
  'saturation_normalized_timespan_dcterms_haspart' => 'Multilingual saturation of Timespan/dcterms:hasPart (normalized average)',
  'saturation_sum_timespan_edm_isnextinsequence' => 'Multilingual saturation of Timespan/edm:isNextInSequence (sum)',
  'saturation_average_timespan_edm_isnextinsequence' => 'Multilingual saturation of Timespan/edm:isNextInSequence (average)',
  'saturation_normalized_timespan_edm_isnextinsequence' => 'Multilingual saturation of Timespan/edm:isNextInSequence (normalized average)',
  'saturation_sum_timespan_owl_sameas' => 'Multilingual saturation of Timespan/owl:sameAs (sum)',
  'saturation_average_timespan_owl_sameas' => 'Multilingual saturation of Timespan/owl:sameAs (average)',
  'saturation_normalized_timespan_owl_sameas' => 'Multilingual saturation of Timespan/owl:sameAs (normalized average)',
  'saturation_sum_timespan_skos_preflabel' => 'Multilingual saturation of Timespan/skos:prefLabel (sum)',
  'saturation_average_timespan_skos_preflabel' => 'Multilingual saturation of Timespan/skos:prefLabel (average)',
  'saturation_normalized_timespan_skos_preflabel' => 'Multilingual saturation of Timespan/skos:prefLabel (normalized average)',
  'saturation_sum_timespan_skos_altlabel' => 'Multilingual saturation of Timespan/skos:altLabel (sum)',
  'saturation_average_timespan_skos_altlabel' => 'Multilingual saturation of Timespan/skos:altLabel (average)',
  'saturation_normalized_timespan_skos_altlabel' => 'Multilingual saturation of Timespan/skos:altLabel (normalized average)',
  'saturation_sum_timespan_skos_note' => 'Multilingual saturation of Timespan/skos:note (sum)',
  'saturation_average_timespan_skos_note' => 'Multilingual saturation of Timespan/skos:note (average)',
  'saturation_normalized_timespan_skos_note' => 'Multilingual saturation of Timespan/skos:note (normalized average)',
  'saturation_sum_concept_skos_broader' => 'Multilingual saturation of Concept/skos:broader (sum)',
  'saturation_average_concept_skos_broader' => 'Multilingual saturation of Concept/skos:broader (average)',
  'saturation_normalized_concept_skos_broader' => 'Multilingual saturation of Concept/skos:broader (normalized average)',
  'saturation_sum_concept_skos_narrower' => 'Multilingual saturation of Concept/skos:narrower (sum)',
  'saturation_average_concept_skos_narrower' => 'Multilingual saturation of Concept/skos:narrower (average)',
  'saturation_normalized_concept_skos_narrower' => 'Multilingual saturation of Concept/skos:narrower (normalized average)',
  'saturation_sum_concept_skos_related' => 'Multilingual saturation of Concept/skos:related (sum)',
  'saturation_average_concept_skos_related' => 'Multilingual saturation of Concept/skos:related (average)',
  'saturation_normalized_concept_skos_related' => 'Multilingual saturation of Concept/skos:related (normalized average)',
  'saturation_sum_concept_skos_broadmatch' => 'Multilingual saturation of Concept/skos:broadMatch (sum)',
  'saturation_average_concept_skos_broadmatch' => 'Multilingual saturation of Concept/skos:broadMatch (average)',
  'saturation_normalized_concept_skos_broadmatch' => 'Multilingual saturation of Concept/skos:broadMatch (normalized average)',
  'saturation_sum_concept_skos_narrowmatch' => 'Multilingual saturation of Concept/skos:narrowMatch (sum)',
  'saturation_average_concept_skos_narrowmatch' => 'Multilingual saturation of Concept/skos:narrowMatch (average)',
  'saturation_normalized_concept_skos_narrowmatch' => 'Multilingual saturation of Concept/skos:narrowMatch (normalized average)',
  'saturation_sum_concept_skos_relatedmatch' => 'Multilingual saturation of Concept/skos:relatedMatch (sum)',
  'saturation_average_concept_skos_relatedmatch' => 'Multilingual saturation of Concept/skos:relatedMatch (average)',
  'saturation_normalized_concept_skos_relatedmatch' => 'Multilingual saturation of Concept/skos:relatedMatch (normalized average)',
  'saturation_sum_concept_skos_exactmatch' => 'Multilingual saturation of Concept/skos:exactMatch (sum)',
  'saturation_average_concept_skos_exactmatch' => 'Multilingual saturation of Concept/skos:exactMatch (average)',
  'saturation_normalized_concept_skos_exactmatch' => 'Multilingual saturation of Concept/skos:exactMatch (normalized average)',
  'saturation_sum_concept_skos_closematch' => 'Multilingual saturation of Concept/skos:closeMatch (sum)',
  'saturation_average_concept_skos_closematch' => 'Multilingual saturation of Concept/skos:closeMatch (average)',
  'saturation_normalized_concept_skos_closematch' => 'Multilingual saturation of Concept/skos:closeMatch (normalized average)',
  'saturation_sum_concept_skos_notation' => 'Multilingual saturation of Concept/skos:notation (sum)',
  'saturation_average_concept_skos_notation' => 'Multilingual saturation of Concept/skos:notation (average)',
  'saturation_normalized_concept_skos_notation' => 'Multilingual saturation of Concept/skos:notation (normalized average)',
  'saturation_sum_concept_skos_inscheme' => 'Multilingual saturation of Concept/skos:inScheme (sum)',
  'saturation_average_concept_skos_inscheme' => 'Multilingual saturation of Concept/skos:inScheme (average)',
  'saturation_normalized_concept_skos_inscheme' => 'Multilingual saturation of Concept/skos:inScheme (normalized average)',
  'saturation_sum_concept_skos_preflabel' => 'Multilingual saturation of Concept/skos:prefLabel (sum)',
  'saturation_average_concept_skos_preflabel' => 'Multilingual saturation of Concept/skos:prefLabel (average)',
  'saturation_normalized_concept_skos_preflabel' => 'Multilingual saturation of Concept/skos:prefLabel (normalized average)',
  'saturation_sum_concept_skos_altlabel' => 'Multilingual saturation of Concept/skos:altLabel (sum)',
  'saturation_average_concept_skos_altlabel' => 'Multilingual saturation of Concept/skos:altLabel (average)',
  'saturation_normalized_concept_skos_altlabel' => 'Multilingual saturation of Concept/skos:altLabel (normalized average)',
  'saturation_sum_concept_skos_note' => 'Multilingual saturation of Concept/skos:note (sum)',
  'saturation_average_concept_skos_note' => 'Multilingual saturation of Concept/skos:note (average)',
  'saturation_normalized_concept_skos_note' => 'Multilingual saturation of Concept/skos:note (normalized average)',

  'long_subject' => 'Metadata problem - Long subject',
  'same_title_and_description' => 'Metadata problem - title and description are the same',
  'empty_string' => 'Metadata problem - empty field',
);

$feature = isset($_GET) && isset($_GET['feature']) ? $_GET['feature'] : DEFAULT_FEATURE;
if (!isset($feature) || !isset($features[$feature])) {
  $feature = DEFAULT_FEATURE;
}

$types = [
  'data-providers' => 'Data providers',
  'datasets' => 'Data sets'
];
$type = isset($_GET) && isset($_GET['type']) ? $_GET['type'] : 'data-providers';
if (!isset($type) || !isset($types[$type])) {
  $type = 'data-providers';
}
$prefix = $type == 'datasets' ? 'c' : 'd';

// $csv = array_map('str_getcsv', file('collection-names.csv'));

function parse_csv($t) {
  return str_getcsv($t, ';');
}
$csv = array_map('parse_csv', file($type . '.txt'));

$summaryFile = 'json_cache/index-summary-' . $feature . '-' . $prefix . '.json';
$isSaturation2 = FALSE;
if (preg_match('/^saturation_/', $feature)) {
  $suffix = '.saturation';
} else if (preg_match('/^saturation2_/', $feature)) {
  $suffix = '.saturation';
  $isSaturation2 = TRUE;
} else if (preg_match('/^(weighted|completeness)_/', $feature)) {
  $suffix = '.weighted-completeness';
} else {
  $suffix = '';
}

$datasetLink = $isSaturation2 ? 'multilinguality.php' : 'dataset.php';

$problems = [];
$rows = [];
if (file_exists($summaryFile)) {
  $rows = json_decode(file_get_contents($summaryFile));
} else {
  $counter = 1;
  foreach ($csv as $id => $row) {
    $id = $row[0];
    $collectionId = $row[1];

    $n = 0;
    $jsonCountFileName = $configuration['QA_R_PATH'] . '/json2/' . $prefix . $id . '.count.json';
    if (file_exists($jsonCountFileName)) {
      $stats = json_decode(file_get_contents($jsonCountFileName));
      $n = $stats[0]->count;
    }

    $jsonFileName = $configuration['QA_R_PATH'] . '/json2/' . $prefix . $id . $suffix . '.json';
    if (file_exists($jsonFileName)) {
      if ($counter == 1) {
        // echo 'jsonFileName: ', $jsonFileName, "\n";
      }
      $stats = json_decode(file_get_contents($jsonFileName));
      $assocStat = array();
      foreach ($stats as $obj) {
        if ($counter == 1) {
          // echo json_encode($obj);
        }
        if ($obj->_row == $feature) {
          unset($obj->recMin);
          unset($obj->recMax);
          unset($obj->_row);
          $obj->n = $n;
          $obj->id = $id;
          $obj->type = $prefix;
          $obj->collectionId = $collectionId;
          $rows[$counter++] = $obj;
          break;
        }
      }
    } else {
      $problems[] = sprintf("jsonFileName (%s) is not existing\n", $jsonFileName);
    }
  }
  // echo 'count: ', count($rows), "\n";
  // if ($suffix != '.weighted-completeness' && $suffix != '.saturation')
  file_put_contents($summaryFile, json_encode($rows));
}

include("templates/v1.0/index/index.tpl.php");
