<?php
$templateDir = '../templates/newviz/cardinality/';

// 'Concept_rdf_about', 'Timespan_rdf_about',
$fields = [
  'general' => [
    'aggregated' => 'All fields aggregated',
    'identifier' => 'identifier',
  ],

  'ProvidedCHO' => [
    'proxy_dc_contributor' => 'dc:contributor',
    'proxy_dc_coverage' => 'dc:coverage',
    'proxy_dc_creator' => 'dc:creator',
    'proxy_dc_date' => 'dc:date',
    'proxy_dc_description' => 'dc:description',
    'proxy_dc_format' => 'dc:format',
    'proxy_dc_identifier' => 'dc:identifier',
    'proxy_dc_language' => 'dc:language',
    'proxy_dc_publisher' => 'dc:publisher',
    'proxy_dc_relation' => 'dc:relation',
    'proxy_dc_rights' => 'dc:rights',
    'proxy_dc_source' => 'dc:source',
    'proxy_dc_subject' => 'dc:subject',
    'proxy_dc_title' => 'dc:title',
    'proxy_dc_type' => 'dc:type',
    'proxy_dcterms_alternative' => 'dcterms:alternative',
    'proxy_dcterms_conformsto' => 'dcterms:conformsTo',
    'proxy_dcterms_created' => 'dcterms:created',
    'proxy_dcterms_extent' => 'dcterms:extent',
    'proxy_dcterms_hasFormat' => 'dcterms:hasFormat',
    'proxy_dcterms_hasPart' => 'dcterms:hasPart',
    'proxy_dcterms_hasVersion' => 'dcterms:hasVersion',
    'proxy_dcterms_isFormatOf' => 'dcterms:isFormatOf',
    'proxy_dcterms_isPartOf' => 'dcterms:isPartOf',
    'proxy_dcterms_isReferencedBy' => 'dcterms:isReferencedBy',
    'proxy_dcterms_isReplacedBy' => 'dcterms:isReplacedBy',
    'proxy_dcterms_isRequiredBy' => 'dcterms:isRequiredBy',
    'proxy_dcterms_issued' => 'dcterms:issued',
    'proxy_dcterms_isVersionOf' => 'dcterms:isVersionOf',
    'proxy_dcterms_medium' => 'dcterms:medium',
    'proxy_dcterms_provenance' => 'dcterms:provenance',
    'proxy_dcterms_references' => 'dcterms:references',
    'proxy_dcterms_replaces' => 'dcterms:replaces',
    'proxy_dcterms_requires' => 'dcterms:requires',
    'proxy_dcterms_spatial' => 'dcterms:spatial',
    'proxy_dcterms_tableOfContents' => 'dcterms:tableOfContents',
    'proxy_dcterms_temporal' => 'dcterms:temporal',
    'proxy_edm_currentLocation' => 'edm:currentLocation',
    // 'proxy_edm_europeanaProxy' => 'edm:europeanaProxy',
    'proxy_edm_hasMet' => 'edm:hasMet',
    'proxy_edm_hasType' => 'edm:hasType',
    'proxy_edm_incorporates' => 'edm:incorporates',
    'proxy_edm_isDerivativeOf' => 'edm:isDerivativeOf',
    'proxy_edm_isNextInSequence' => 'edm:isNextInSequence',
    'proxy_edm_isRelatedTo' => 'edm:isRelatedTo',
    'proxy_edm_isRepresentationOf' => 'edm:isRepresentationOf',
    'proxy_edm_isSimilarTo' => 'edm:isSimilarTo',
    'proxy_edm_isSuccessorOf' => 'edm:isSuccessorOf',
    'proxy_edm_realizes' => 'edm:realizes',
    'proxy_edm_type' => 'edm:type',
    // 'proxy_edm_userTag' => 'edm:userTag',
    // 'proxy_edm_wasPresentAt' => 'edm:wasPresentAt',
    // 'proxy_edm_year' => 'edm:year',
    // 'proxy_ore_ProxyFor' => 'ore:ProxyFor',
    // 'proxy_ore_ProxyIn' => 'ore:ProxyIn',
    // owl:sameAs
  ],
  'Aggregation' => [
    'aggregation_edm_aggregatedCHO' => 'edm:aggregatedCHO',
    'aggregation_edm_dataProvider' => 'edm:dataProvider',
    'aggregation_edm_provider' => 'edm:provider',
    'aggregation_dc_rights' => 'dc:rights',
    'aggregation_edm_hasView' => 'edm:hasView',
    'aggregation_edm_isShownAt' => 'edm:isShownAt',
    'aggregation_edm_isShownBy' => 'edm:isShownBy',
    'aggregation_edm_object' => 'edm:object',
    'aggregation_edm_rights' => 'edm:rights',
    'aggregation_edm_ugc' => 'edm:ugc',
    'aggregation_edm_intermediateProvider' => 'edm:intermediateProvider',
  ],
  'Agent' => [
    'agent_skos_prefLabel' => 'skos:prefLabel',
    'agent_skos_altLabel' => 'skos:altLabel',
    'agent_skos_note' => 'skos:note',
    'agent_dc_date' => 'dc:date',
    'agent_dc_identifier' => 'dc:identifier',
    // dcterms:hasPart
    // dcterms:isPartOf
    'agent_edm_begin' => 'edm:begin',
    'agent_edm_end' => 'edm:end',
    'agent_edm_hasMet' => 'edm:hasMet',
    'agent_edm_isRelatedTo' => 'edm:isRelatedTo',
    'agent_foaf_name' => 'foaf:name',
    'agent_rdaGr2_biographicalInformation' => 'rdaGr2:biographicalInformation',
    'agent_rdaGr2_dateOfBirth' => 'rdaGr2:dateOfBirth',
    'agent_rdaGr2_dateOfDeath' => 'rdaGr2:dateOfDeath',
    'agent_rdaGr2_dateOfEstablishment' => 'rdaGr2:dateOfEstablishment',
    'agent_rdaGr2_dateOfTermination' => 'rdaGr2:dateOfTermination',
    'agent_rdaGr2_gender' => 'rdaGr2:gender',
    'agent_rdaGr2_placeOfBirth' => 'rdaGr2:placeOfBirth',
    'agent_rdaGr2_placeOfDeath' => 'rdaGr2:placeOfDeath',
    'agent_rdaGr2_professionOrOccupation' => 'rdaGr2:professionOrOccupation',
    'agent_owl_sameAs' => 'owl:sameAs',
  ],
  'Concept' => [
    'concept_skos_prefLabel' => 'skos:prefLabel',
    'concept_skos_altLabel' => 'skos:altLabel',
    'concept_skos_broader' => 'skos:broader',
    'concept_skos_narrower' => 'skos:narrower',
    'concept_skos_related' => 'skos:related',
    'concept_skos_broadMatch' => 'skos:broadMatch',
    'concept_skos_narrowMatch' => 'skos:narrowMatch',
    'concept_skos_relatedMatch' => 'skos:relatedMatch',
    'concept_skos_exactMatch' => 'skos:exactMatch',
    'concept_skos_closeMatch' => 'skos:closeMatch',
    'concept_skos_note' => 'skos:note',
    'concept_skos_notation' => 'skos:notation',
    'concept_skos_inScheme' => 'skos:inScheme',
  ],
  'Place' => [
    'place_wgs84_lat' => 'wgs84_pos:lat',
    'place_wgs84_long' => 'wgs84_pos:long',
    'place_wgs84_alt' => 'wgs84_pos:alt',
    'place_skos_prefLabel' => 'skos:prefLabel',
    'place_skos_altLabel' => 'skos:altLabel',
    'place_skos_note' => 'skos:note',
    'place_dcterms_hasPart' => 'dcterms:hasPart',
    'place_dcterms_isPartOf' => 'dcterms:isPartOf',
    // edm:isNextInSequence
    'place_owl_sameas' => 'owl:sameAs',
  ],
  'Timespan' => [
    'timespan_skos_prefLabel' => 'skos:prefLabel',
    'timespan_skos_altLabel' => 'skos:altLabel',
    'timespan_edm_begin' => 'edm:begin',
    'timespan_edm_end' => 'edm:end',
    'timespan_skos_note' => 'skos:note',
    'timespan_dcterms_hasPart' => 'dcterms:hasPart',
    'timespan_dcterms_isPartOf' => 'dcterms:isPartOf',
    'timespan_edm_isNextInSequence' => 'edm:isNextInSequence',
    'timespan_owl_sameAs' => 'owl:sameAs',
  ],
];

$mandatory = [
  'ProvidedCHO' => [
    'proxy_dc_language' => 'black',
    'proxy_edm_type' => 'black',
    'proxy_dc_description' => 'blue',
    'proxy_dc_title' => 'blue',
    'proxy_dc_subject' => 'red',
    'proxy_dc_type' => 'red',
    'proxy_dcterms_spatial' => 'red',
    'proxy_dcterms_temporal' => 'red',
    'proxy_dc_contributor' => 'plus',
    'proxy_dc_creator' => 'plus',
    'proxy_dc_date' => 'plus',
    'proxy_dc_identifier' => 'plus',
    'proxy_dc_publisher' => 'plus',
    'proxy_dc_source' => 'plus',
    'proxy_dcterms_alternative' => 'plus',
    'proxy_dcterms_created' => 'plus',
    'proxy_dcterms_ispartof' => 'plus',
    'proxy_dcterms_issued' => 'plus',
    'proxy_edm_isnextinsequence' => 'plus',
  ],
  'Aggregation' => [
    'aggregation_edm_aggregatedcho' => 'black',
    'aggregation_edm_dataprovider' => 'black',
    'aggregation_edm_provider' => 'black',
    'aggregation_edm_rights' => 'black',
    'aggregation_edm_isshownat' => 'green',
    'aggregation_edm_isshownby' => 'green',
  ],
  'Agent' => [
    'agent_skos_preflabel' => 'plus',
    'agent_skos_altlabel' => 'plus',
    'agent_rdagr2_dateofbirth' => 'plus',
    'agent_rdagr2_dateofdeath' => 'plus',
  ],
  'Concept' => [
    'concept_skos_preflabel' => 'plus',
    'concept_skos_altlabel' => 'plus',
  ],
  'Place' => [
    'place_wgs84_lat' => 'plus',
    'place_wgs84_long' => 'plus',
    'place_skos_preflabel' => 'plus',
  ],
  'Timespan' => [
    'timespan_skos_preflabel' => 'plus',
    'timespan_edm_begin' => 'plus',
    'timespan_edm_end' => 'plus',
  ],
];