<?php

$field_scopes = [
  'provider' => 'Provider proxy',
  'europeana' => 'Europeana proxy',
];

$field_metrics = [
  'taggedliterals' => 'tagged literals',
  'languages' => 'languages',
  'literalsperlanguage' => 'literals per language',
];

$fields = [
  'dc_title' => 'dc:title',
  'dcterms_alternative' => 'dcterms:alternative',
  'dc_description' => 'dc:description',
  'dc_creator' => 'dc:creator',
  'dc_publisher' => 'dc:publisher',
  'dc_contributor' => 'dc:contributor',
  'dc_type' => 'dc:type',
  'dc_identifier' => 'dc:identifier',
  'dc_language' => 'dc:language',
  'dc_coverage' => 'dc:coverage',
  'dcterms_temporal' => 'dcterms:temporal',
  'dcterms_spatial' => 'dcterms:spatial',
  'dc_subject' => 'dc:subject',
  'dc_date' => 'dc:date',
  'dcterms_created' => 'dcterms:created',
  'dcterms_issued' => 'dcterms:issued',
  'dcterms_extent' => 'dcterms:extent',
  'dcterms_medium' => 'dcterms:medium',
  'dcterms_provenance' => 'dcterms:provenance',
  'dcterms_hasPart' => 'dcterms:hasPart',
  'dcterms_isPartOf' => 'dcterms:isPartOf',
  'dc_format' => 'dc:format',
  'dc_source' => 'dc:source',
  'dc_rights' => 'dc:rights',
  'dc_relation' => 'dc:relation',
  'edm_year' => 'edm:year',
  'edm_userTag' => 'edm:userTag',
  'dc_conformsTo' => 'dc:conformsTo',
  'dcterms_hasFormat' => 'dcterms:hasFormat',
  'dcterms_hasVersion' => 'dcterms:hasVersion',
  'dcterms_isFormatOf' => 'dcterms:isFormatOf',
  'dcterms_isReferencedBy' => 'dcterms:isReferencedBy',
  'dcterms_isReplacedBy' => 'dcterms:isReplacedBy',
  'dcterms_isRequiredBy' => 'dcterms:isRequiredBy',
  'dcterms_isVersionOf' => 'dcterms:isVersionOf',
  'dcterms_references' => 'dcterms:references',
  'dcterms_replaces' => 'dcterms:replaces',
  'dcterms_requires' => 'dcterms:requires',
  'dcterms_tableOfContents' => 'dcterms:tableOfContents',
  'edm_currentLocation' => 'edm:currentLocation',
  'edm_hasMet' => 'edm:hasMet',
  'edm_hasType' => 'edm:hasType',
  'edm_incorporates' => 'edm:incorporates',
  'edm_isDerivativeOf' => 'edm:isDerivativeOf',
  'edm_isRelatedTo' => 'edm:isRelatedTo',
  'edm_isRepresentationOf' => 'edm:isRepresentationOf',
  'edm_isSimilarTo' => 'edm:isSimilarTo',
  'edm_isSuccessorOf' => 'edm:isSuccessorOf',
  'edm_realizes' => 'edm:realizes',
  'edm_wasPresentAt' => 'edm:wasPresentAt',
];
